# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 03:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author_Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_image', models.CharField(max_length=125)),
                ('birthday', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=156, verbose_name='轮播图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_view', models.BooleanField(default=False, verbose_name='是否显示')),
            ],
        ),
        migrations.CreateModel(
            name='Boke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=125, null=True, verbose_name='标题')),
                ('image', models.CharField(max_length=156, verbose_name='封面图片')),
                ('describe', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('content', models.TextField(verbose_name='博客内容')),
                ('give_num', models.IntegerField(verbose_name='点赞')),
                ('author', models.CharField(max_length=125, verbose_name='博主')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('boke_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokeapp.Boke')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('login_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='姓名')),
                ('password', models.CharField(max_length=24, verbose_name='密码')),
                ('birthday', models.DateField(default=datetime.datetime.now, verbose_name='出生年月')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, unique=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bokeapp.User'),
        ),
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokeapp.User'),
        ),
        migrations.AddField(
            model_name='boke',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokeapp.Category'),
        ),
        migrations.AddField(
            model_name='banner',
            name='boke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokeapp.Boke', verbose_name='博客'),
        ),
        migrations.AddField(
            model_name='author_center',
            name='boke_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokeapp.Boke'),
        ),
    ]
